//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIM.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MW_LEFT {
            get {
                return ((double)(this["MW_LEFT"]));
            }
            set {
                this["MW_LEFT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MW_TOP {
            get {
                return ((double)(this["MW_TOP"]));
            }
            set {
                this["MW_TOP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double MW_WIDTH {
            get {
                return ((double)(this["MW_WIDTH"]));
            }
            set {
                this["MW_WIDTH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public double MW_HEIGHT {
            get {
                return ((double)(this["MW_HEIGHT"]));
            }
            set {
                this["MW_HEIGHT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\ni88\\Desktop\\")]
        public string optionsT1_source {
            get {
                return ((string)(this["optionsT1_source"]));
            }
            set {
                this["optionsT1_source"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\ni88\\Desktop\\custom\\")]
        public string optionsT1_destination {
            get {
                return ((string)(this["optionsT1_destination"]));
            }
            set {
                this["optionsT1_destination"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool optionsT1_Feature1_check {
            get {
                return ((bool)(this["optionsT1_Feature1_check"]));
            }
            set {
                this["optionsT1_Feature1_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool optionsT1_Feature2_check {
            get {
                return ((bool)(this["optionsT1_Feature2_check"]));
            }
            set {
                this["optionsT1_Feature2_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool optionsT1_Feature3_check {
            get {
                return ((bool)(this["optionsT1_Feature3_check"]));
            }
            set {
                this["optionsT1_Feature3_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool optionsT1_Feature4_check {
            get {
                return ((bool)(this["optionsT1_Feature4_check"]));
            }
            set {
                this["optionsT1_Feature4_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool optionsT1_Feature5_check {
            get {
                return ((bool)(this["optionsT1_Feature5_check"]));
            }
            set {
                this["optionsT1_Feature5_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool optionsT1_Feature6_check {
            get {
                return ((bool)(this["optionsT1_Feature6_check"]));
            }
            set {
                this["optionsT1_Feature6_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool optionsT1_Feature7_check {
            get {
                return ((bool)(this["optionsT1_Feature7_check"]));
            }
            set {
                this["optionsT1_Feature7_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool optionsT1_Feature8_check {
            get {
                return ((bool)(this["optionsT1_Feature8_check"]));
            }
            set {
                this["optionsT1_Feature8_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool optionsT1_Feature9_check {
            get {
                return ((bool)(this["optionsT1_Feature9_check"]));
            }
            set {
                this["optionsT1_Feature9_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string syncxml_Info {
            get {
                return ((string)(this["syncxml_Info"]));
            }
            set {
                this["syncxml_Info"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool optionsT3_Feature1_check {
            get {
                return ((bool)(this["optionsT3_Feature1_check"]));
            }
            set {
                this["optionsT3_Feature1_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool optionsT3_Feature2_check {
            get {
                return ((bool)(this["optionsT3_Feature2_check"]));
            }
            set {
                this["optionsT3_Feature2_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool optionsT3_Feature3_check {
            get {
                return ((bool)(this["optionsT3_Feature3_check"]));
            }
            set {
                this["optionsT3_Feature3_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool optionsT3_Feature4_check {
            get {
                return ((bool)(this["optionsT3_Feature4_check"]));
            }
            set {
                this["optionsT3_Feature4_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Public\\Documents\\")]
        public string optionsT3_Feature5 {
            get {
                return ((string)(this["optionsT3_Feature5"]));
            }
            set {
                this["optionsT3_Feature5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\ni88\\Desktop\\workspace\\")]
        public string optionsT3_Feature6 {
            get {
                return ((string)(this["optionsT3_Feature6"]));
            }
            set {
                this["optionsT3_Feature6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".H")]
        public string optionsT3_Feature7 {
            get {
                return ((string)(this["optionsT3_Feature7"]));
            }
            set {
                this["optionsT3_Feature7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HSNI-WIN\\SQLEXPRESS")]
        public string SQL_DATASOURCE {
            get {
                return ((string)(this["SQL_DATASOURCE"]));
            }
            set {
                this["SQL_DATASOURCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("VC")]
        public string SQL_DATABASE {
            get {
                return ((string)(this["SQL_DATABASE"]));
            }
            set {
                this["SQL_DATABASE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Nirschl")]
        public string SQL_USER {
            get {
                return ((string)(this["SQL_USER"]));
            }
            set {
                this["SQL_USER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("U111")]
        public string SQL_PASSWORD {
            get {
                return ((string)(this["SQL_PASSWORD"]));
            }
            set {
                this["SQL_PASSWORD"] = value;
            }
        }
    }
}
